### PR TITLE
C4DM webpage for the Chinese Bamboo Flute Dataset

### PR DESCRIPTION
**Pull request by changhongw**
This the official C4DM webpage we create for the Chinese bamboo flute dataset. Please add to the c4dm website, thanks! -- Changhong Wang, Emmanoil Benetos, Elaine Chew

### CODE REVIEW

**Comment by danstowell** [comment]
Hi Changhong - could we make two changes to this before merging, please? First is that you do not need to include all the HTML for the webpage "template" into the page itself. If you write the page with file extension ".md" instead of ".html", the system will automatically render the template around it. Look at other examples in the website repository to see more examples of how it works.

Secondly, I'd prefer not to put it in the root directory, so may we rename it to "downloads/CBFdataset.md" to put it in a downloads subfolder? That seems neater to me.

**Comment by changhongw** [comment]
Hi Dan, many thanks for the suggestions! No problem with the first change. 

But for the second one, we couldn't rename the file to "downloads/CBFdataset.md" because the generated URL would be http://c4dm.eecs.qmul.ac.uk/downloads/CBFdataset.html.  In our published papers, we have already used http://c4dm.eecs.qmul.ac.uk/CBFdataset.html. If we changed the URL, the readers would not be able to find the dataset. 

Let's leave the "CBFdataset.html" in frank folder without merging to the root directory on github. :)

**Comment by danstowell** [comment]
I see. OK. We can merge it into the github though, if you make a markdown version. Merging it makes it less likely to get lost in future!

**Comment by changhongw** [comment]
That's great! Thanks, Dan!

**Comment by changhongw** [comment]
> I see. OK. We can merge it into the github though, if you make a markdown version. Merging it makes it less likely to get lost in future!



> I see. OK. We can merge it into the github though, if you make a markdown version. Merging it makes it less likely to get lost in future!

That's great! Thanks a lot, Dan!

**Comment by changhongw** [comment]
> I see. OK. We can merge it into the github though, if you make a markdown version. Merging it makes it less likely to get lost in future!

That's great! Thanks a lot, Dan!

**Pull request merged**
