### PR TITLE
Add beici publications

### PR DESCRIPTION
**Pull request by beiciliang**
Add three missing publicaitons of myself. Thanks!

### CODE REVIEW

**Comment by danstowell** [comment]
Thanks. This pull request failed because your own copy of the website code was way behind the official copy. I had to copy and paste the info manually. It's useful to try and "git merge" the official `c4dm/c4dmpoole` into `beiciliang/c4dmpoole` to make sure it's up-to-date before making edits. (Sorry, added complexity.)

**Comment by danstowell** [comment]
P.S. I did add your data now

**Comment by beiciliang** [comment]
Thanks for the tip and sorry for the inconvenience... I did the fork only on github and forgot to clone locally, and there are no tools for doing merges through the web interface. I will do the upstream merge locally, push the changes back to my fork, and then raise a pull request for further updates! (If this could make sure to avoid pull request fail!)

**Comment by danstowell** [comment]
No problem - this is a bit more tricky in practice than I thought it would be...

**Pull request closed without merging**
