### PR TITLE
Create news.2018-11-21.Mathieu Lagrange Seminar.md

### PR DESCRIPTION
**Pull request by koohqm**

### CODE REVIEW

**Comment by danstowell** [comment]
Hi Ken, do you want me to merge this? I think you have permissions to merge it yourself but maybe I'm wrong...

**Comment by koohqm** [comment]
Hi Dan, Would be great if you could....

I think I do have the permission to do it -

but not sure if I know how to; otherwise put - can't find

a menu item, after significant search, that allows me to!

Best,

Ken


________________________________

**Comment by danstowell** [comment]
I see. Here I see a big green button "Rebase and merge", and that's the one I normally press

**Comment by koohqm** [comment]
Thanks, I don’t recall seeing that one.
Maybe because I was in a fork or something?
Sorry, I’ve never really got to grips with github!

On 12 Nov 2018, at 18:50, danstowell <notifications@github.com<mailto:notifications@github.com>> wrote:


I see. Here I see a big green button "Rebase and merge", and that's the one I normally press

**Pull request merged**
